package com.barbre.fiddle.io;

import com.barbre.fiddle.elements.IButtonDrawTemplate;
import com.barbre.fiddle.elements.IUi2DAnimation;
import com.barbre.fiddle.elements.IUi2DAnimation;
import com.barbre.fiddle.elements.IUi2DAnimation;
import com.barbre.fiddle.elements.IUi2DAnimation;
import com.barbre.fiddle.elements.IUi2DAnimation;
import com.barbre.fiddle.elements.IUi2DAnimation;
import com.barbre.fiddle.elements.IUi2DAnimation;
import com.barbre.fiddle.elements.IUi2DAnimation;
import com.barbre.fiddle.elements.IUi2DAnimation;
import com.barbre.fiddle.elements.IUi2DAnimation;

/**
 * Generated by BeanBuilder for SIDL Fiddle
 */
public class EQButtonDrawTemplate extends EQClass implements IButtonDrawTemplate {
	private String Normal;
	private IUi2DAnimation NormalObject;
	private String Pressed;
	private IUi2DAnimation PressedObject;
	private String Flyby;
	private IUi2DAnimation FlybyObject;
	private String Disabled;
	private IUi2DAnimation DisabledObject;
	private String PressedFlyby;
	private IUi2DAnimation PressedFlybyObject;
	private String NormalDecal;
	private IUi2DAnimation NormalDecalObject;
	private String PressedDecal;
	private IUi2DAnimation PressedDecalObject;
	private String FlybyDecal;
	private IUi2DAnimation FlybyDecalObject;
	private String DisabledDecal;
	private IUi2DAnimation DisabledDecalObject;
	private String PressedFlybyDecal;
	private IUi2DAnimation PressedFlybyDecalObject;

	public String getNormal() {
		return Normal;
	}

	public void setNormal(String value) {
		String old = Normal;
		Normal = value;
		firePropertyChange("Normal", old, Normal);
	}

	public IUi2DAnimation getNormalObject() {
		return NormalObject;
	}

	public void setNormalObject(IUi2DAnimation value) {
		IUi2DAnimation old = NormalObject;
		NormalObject = value;
		firePropertyChange("NormalObject", old, NormalObject);
	}

	public String getPressed() {
		return Pressed;
	}

	public void setPressed(String value) {
		String old = Pressed;
		Pressed = value;
		firePropertyChange("Pressed", old, Pressed);
	}

	public IUi2DAnimation getPressedObject() {
		return PressedObject;
	}

	public void setPressedObject(IUi2DAnimation value) {
		IUi2DAnimation old = PressedObject;
		PressedObject = value;
		firePropertyChange("PressedObject", old, PressedObject);
	}

	public String getFlyby() {
		return Flyby;
	}

	public void setFlyby(String value) {
		String old = Flyby;
		Flyby = value;
		firePropertyChange("Flyby", old, Flyby);
	}

	public IUi2DAnimation getFlybyObject() {
		return FlybyObject;
	}

	public void setFlybyObject(IUi2DAnimation value) {
		IUi2DAnimation old = FlybyObject;
		FlybyObject = value;
		firePropertyChange("FlybyObject", old, FlybyObject);
	}

	public String getDisabled() {
		return Disabled;
	}

	public void setDisabled(String value) {
		String old = Disabled;
		Disabled = value;
		firePropertyChange("Disabled", old, Disabled);
	}

	public IUi2DAnimation getDisabledObject() {
		return DisabledObject;
	}

	public void setDisabledObject(IUi2DAnimation value) {
		IUi2DAnimation old = DisabledObject;
		DisabledObject = value;
		firePropertyChange("DisabledObject", old, DisabledObject);
	}

	public String getPressedFlyby() {
		return PressedFlyby;
	}

	public void setPressedFlyby(String value) {
		String old = PressedFlyby;
		PressedFlyby = value;
		firePropertyChange("PressedFlyby", old, PressedFlyby);
	}

	public IUi2DAnimation getPressedFlybyObject() {
		return PressedFlybyObject;
	}

	public void setPressedFlybyObject(IUi2DAnimation value) {
		IUi2DAnimation old = PressedFlybyObject;
		PressedFlybyObject = value;
		firePropertyChange("PressedFlybyObject", old, PressedFlybyObject);
	}

	public String getNormalDecal() {
		return NormalDecal;
	}

	public void setNormalDecal(String value) {
		String old = NormalDecal;
		NormalDecal = value;
		firePropertyChange("NormalDecal", old, NormalDecal);
	}

	public IUi2DAnimation getNormalDecalObject() {
		return NormalDecalObject;
	}

	public void setNormalDecalObject(IUi2DAnimation value) {
		IUi2DAnimation old = NormalDecalObject;
		NormalDecalObject = value;
		firePropertyChange("NormalDecalObject", old, NormalDecalObject);
	}

	public String getPressedDecal() {
		return PressedDecal;
	}

	public void setPressedDecal(String value) {
		String old = PressedDecal;
		PressedDecal = value;
		firePropertyChange("PressedDecal", old, PressedDecal);
	}

	public IUi2DAnimation getPressedDecalObject() {
		return PressedDecalObject;
	}

	public void setPressedDecalObject(IUi2DAnimation value) {
		IUi2DAnimation old = PressedDecalObject;
		PressedDecalObject = value;
		firePropertyChange("PressedDecalObject", old, PressedDecalObject);
	}

	public String getFlybyDecal() {
		return FlybyDecal;
	}

	public void setFlybyDecal(String value) {
		String old = FlybyDecal;
		FlybyDecal = value;
		firePropertyChange("FlybyDecal", old, FlybyDecal);
	}

	public IUi2DAnimation getFlybyDecalObject() {
		return FlybyDecalObject;
	}

	public void setFlybyDecalObject(IUi2DAnimation value) {
		IUi2DAnimation old = FlybyDecalObject;
		FlybyDecalObject = value;
		firePropertyChange("FlybyDecalObject", old, FlybyDecalObject);
	}

	public String getDisabledDecal() {
		return DisabledDecal;
	}

	public void setDisabledDecal(String value) {
		String old = DisabledDecal;
		DisabledDecal = value;
		firePropertyChange("DisabledDecal", old, DisabledDecal);
	}

	public IUi2DAnimation getDisabledDecalObject() {
		return DisabledDecalObject;
	}

	public void setDisabledDecalObject(IUi2DAnimation value) {
		IUi2DAnimation old = DisabledDecalObject;
		DisabledDecalObject = value;
		firePropertyChange("DisabledDecalObject", old, DisabledDecalObject);
	}

	public String getPressedFlybyDecal() {
		return PressedFlybyDecal;
	}

	public void setPressedFlybyDecal(String value) {
		String old = PressedFlybyDecal;
		PressedFlybyDecal = value;
		firePropertyChange("PressedFlybyDecal", old, PressedFlybyDecal);
	}

	public IUi2DAnimation getPressedFlybyDecalObject() {
		return PressedFlybyDecalObject;
	}

	public void setPressedFlybyDecalObject(IUi2DAnimation value) {
		IUi2DAnimation old = PressedFlybyDecalObject;
		PressedFlybyDecalObject = value;
		firePropertyChange("PressedFlybyDecalObject", old, PressedFlybyDecalObject);
	}

}