package com.barbre.fiddle.io;

import com.barbre.fiddle.elements.IButton;
import com.barbre.fiddle.elements.IButtonDrawTemplate;
import com.barbre.fiddle.elements.IPoint;
import com.barbre.fiddle.elements.ISize;

/**
 * Generated by BeanBuilder for SIDL Fiddle
 */
public class EQButton extends EQControl implements IButton {
	private boolean Style_Checkbox;
	private String RadioGroup;
	private String Text;
	private IButtonDrawTemplate ButtonDrawTemplate;
	private String SoundPressed;
	private String SoundUp;
	private String SoundFlyby;
	private IPoint DecalOffset;
	private ISize DecalSize;

	public EQButton() {
		super();
	}

	public boolean getStyle_Checkbox() {
		return Style_Checkbox;
	}

	public void setStyle_Checkbox(boolean value) {
		boolean old = Style_Checkbox;
		Style_Checkbox = value;
		firePropertyChange("Style_Checkbox", old, Style_Checkbox);
	}

	public String getRadioGroup() {
		return RadioGroup;
	}

	public void setRadioGroup(String value) {
		String old = RadioGroup;
		RadioGroup = value;
		firePropertyChange("RadioGroup", old, RadioGroup);
	}

	public String getText() {
		return Text;
	}

	public void setText(String value) {
		String old = Text;
		Text = value;
		firePropertyChange("Text", old, Text);
	}

	public IButtonDrawTemplate getButtonDrawTemplate() {
		return ButtonDrawTemplate;
	}

	public void setButtonDrawTemplate(IButtonDrawTemplate value) {
		IButtonDrawTemplate old = ButtonDrawTemplate;
		ButtonDrawTemplate = value;
		firePropertyChange("ButtonDrawTemplate", old, ButtonDrawTemplate);
	}

	public String getSoundPressed() {
		return SoundPressed;
	}

	public void setSoundPressed(String value) {
		String old = SoundPressed;
		SoundPressed = value;
		firePropertyChange("SoundPressed", old, SoundPressed);
	}

	public String getSoundUp() {
		return SoundUp;
	}

	public void setSoundUp(String value) {
		String old = SoundUp;
		SoundUp = value;
		firePropertyChange("SoundUp", old, SoundUp);
	}

	public String getSoundFlyby() {
		return SoundFlyby;
	}

	public void setSoundFlyby(String value) {
		String old = SoundFlyby;
		SoundFlyby = value;
		firePropertyChange("SoundFlyby", old, SoundFlyby);
	}

	public IPoint getDecalOffset() {
		return DecalOffset;
	}

	public void setDecalOffset(IPoint value) {
		IPoint old = DecalOffset;
		DecalOffset = value;
		firePropertyChange("DecalOffset", old, DecalOffset);
	}

	public ISize getDecalSize() {
		return DecalSize;
	}

	public void setDecalSize(ISize value) {
		ISize old = DecalSize;
		DecalSize = value;
		firePropertyChange("DecalSize", old, DecalSize);
	}

}