package com.barbre.fiddle.io;

import com.barbre.fiddle.elements.IClass;

/**
 * Generated by BeanBuilder for SIDL Fiddle
 */
public class EQClass extends EQNode implements IClass {
	private String item;

	public String getitem() {
		return item;
	}

	public void setitem(String value) {
		String old = item;
		item = value;
		firePropertyChange("item", old, item);
	}


}