
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.ICombobox;
			import com.barbre.fiddle.elements.IButtonDrawTemplate;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQCombobox extends EQControl implements ICombobox {
					private String Button;
	private IButtonDrawTemplate ButtonObject;
	private int ListHeight;
	private String[] Choices;

				
				
			public String getButton() {
				return Button;
			}
		
			public void setButton(String value) {
				String old = Button;
				Button = value;
				firePropertyChange("Button", old, Button);
			}
		
			public IButtonDrawTemplate getButtonObject() {				
				return ButtonObject;
			}
		
			public void setButtonObject(IButtonDrawTemplate value) {
				IButtonDrawTemplate old = ButtonObject;
				ButtonObject = value;
				firePropertyChange("ButtonObject", old, ButtonObject);
			}
		
			public int getListHeight() {
				return ListHeight;
			}
		
			public void setListHeight(int value) {
				int old = ListHeight;
				ListHeight = value;
				firePropertyChange("ListHeight", old, ListHeight);
			}
		
			public String[] getChoices() {
				return Choices;
			}
		
			public void setChoices(String[] value) {
				String[] old = Choices;
				Choices = value;
				firePropertyChange("Choices", old, Choices);
			}
		
			public String getChoices(int index) {
				return Choices[index];
			}
		
			public void setChoices(int index, String value) {
				String[] old = Choices;
				Choices[index] = value;
				firePropertyChange("Choices", old, Choices);
			}
		
			}
		