
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IEditbox;
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQEditbox extends EQControl implements IEditbox {
					private boolean Style_Multiline;

				
				
			public boolean getStyle_Multiline() {
				return Style_Multiline;
			}
		
			public void setStyle_Multiline(boolean value) {
				boolean old = Style_Multiline;
				Style_Multiline = value;
				firePropertyChange("Style_Multiline", old, Style_Multiline);
			}
		
			}
		