package com.barbre.fiddle.io;

import com.barbre.fiddle.elements.IFrame;
import com.barbre.fiddle.elements.IPoint;
import com.barbre.fiddle.elements.ISize;
import com.barbre.fiddle.elements.IPoint;
import com.barbre.fiddle.elements.IRGB;
import com.barbre.fiddle.elements.IRGB;

/**
 * Generated by BeanBuilder for SIDL Fiddle
 */
public class EQFrame extends EQClass implements IFrame {
	private String Texture;
	private IPoint Location;
	private ISize Size;
	private IPoint Hotspot;
	private int Duration;
	private IRGB[] Shading;
	private IRGB[] Specular;

	public String getTexture() {
		return Texture;
	}

	public void setTexture(String value) {
		String old = Texture;
		Texture = value;
		firePropertyChange("Texture", old, Texture);
	}

	public IPoint getLocation() {
		return Location;
	}

	public void setLocation(IPoint value) {
		IPoint old = Location;
		Location = value;
		firePropertyChange("Location", old, Location);
	}

	public ISize getSize() {
		return Size;
	}

	public void setSize(ISize value) {
		ISize old = Size;
		Size = value;
		firePropertyChange("Size", old, Size);
	}

	public IPoint getHotspot() {
		return Hotspot;
	}

	public void setHotspot(IPoint value) {
		IPoint old = Hotspot;
		Hotspot = value;
		firePropertyChange("Hotspot", old, Hotspot);
	}

	public int getDuration() {
		return Duration;
	}

	public void setDuration(int value) {
		int old = Duration;
		Duration = value;
		firePropertyChange("Duration", old, Duration);
	}

	public IRGB[] getShading() {
		return Shading;
	}

	public void setShading(IRGB[] value) {
		IRGB[] old = Shading;
		Shading = value;
		firePropertyChange("Shading", old, Shading);
	}

	public IRGB getShading(int index) {
		return Shading[index];
	}

	public void setShading(int index, IRGB value) {
		IRGB[] old = Shading;
		Shading[index] = value;
		firePropertyChange("Shading", old, Shading);
	}

	public IRGB[] getSpecular() {
		return Specular;
	}

	public void setSpecular(IRGB[] value) {
		IRGB[] old = Specular;
		Specular = value;
		firePropertyChange("Specular", old, Specular);
	}

	public IRGB getSpecular(int index) {
		return Specular[index];
	}

	public void setSpecular(int index, IRGB value) {
		IRGB[] old = Specular;
		Specular[index] = value;
		firePropertyChange("Specular", old, Specular);
	}

}