
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IFrameTemplate;
			import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQFrameTemplate extends EQClass implements IFrameTemplate {
					private String TopLeft;
	private IUi2DAnimation TopLeftObject;
	private String Top;
	private IUi2DAnimation TopObject;
	private String TopRight;
	private IUi2DAnimation TopRightObject;
	private String RightTop;
	private IUi2DAnimation RightTopObject;
	private String Right;
	private IUi2DAnimation RightObject;
	private String RightBottom;
	private IUi2DAnimation RightBottomObject;
	private String BottomRight;
	private IUi2DAnimation BottomRightObject;
	private String Bottom;
	private IUi2DAnimation BottomObject;
	private String BottomLeft;
	private IUi2DAnimation BottomLeftObject;
	private String LeftTop;
	private IUi2DAnimation LeftTopObject;
	private String Left;
	private IUi2DAnimation LeftObject;
	private String LeftBottom;
	private IUi2DAnimation LeftBottomObject;
	private String Middle;
	private IUi2DAnimation MiddleObject;
	private int OverlapLeft;
	private int OverlapTop;
	private int OverlapRight;
	private int OverlapBottom;

				
				
			public String getTopLeft() {
				return TopLeft;
			}
		
			public void setTopLeft(String value) {
				String old = TopLeft;
				TopLeft = value;
				firePropertyChange("TopLeft", old, TopLeft);
			}
		
			public IUi2DAnimation getTopLeftObject() {				
				return TopLeftObject;
			}
		
			public void setTopLeftObject(IUi2DAnimation value) {
				IUi2DAnimation old = TopLeftObject;
				TopLeftObject = value;
				firePropertyChange("TopLeftObject", old, TopLeftObject);
			}
		
			public String getTop() {
				return Top;
			}
		
			public void setTop(String value) {
				String old = Top;
				Top = value;
				firePropertyChange("Top", old, Top);
			}
		
			public IUi2DAnimation getTopObject() {				
				return TopObject;
			}
		
			public void setTopObject(IUi2DAnimation value) {
				IUi2DAnimation old = TopObject;
				TopObject = value;
				firePropertyChange("TopObject", old, TopObject);
			}
		
			public String getTopRight() {
				return TopRight;
			}
		
			public void setTopRight(String value) {
				String old = TopRight;
				TopRight = value;
				firePropertyChange("TopRight", old, TopRight);
			}
		
			public IUi2DAnimation getTopRightObject() {				
				return TopRightObject;
			}
		
			public void setTopRightObject(IUi2DAnimation value) {
				IUi2DAnimation old = TopRightObject;
				TopRightObject = value;
				firePropertyChange("TopRightObject", old, TopRightObject);
			}
		
			public String getRightTop() {
				return RightTop;
			}
		
			public void setRightTop(String value) {
				String old = RightTop;
				RightTop = value;
				firePropertyChange("RightTop", old, RightTop);
			}
		
			public IUi2DAnimation getRightTopObject() {				
				return RightTopObject;
			}
		
			public void setRightTopObject(IUi2DAnimation value) {
				IUi2DAnimation old = RightTopObject;
				RightTopObject = value;
				firePropertyChange("RightTopObject", old, RightTopObject);
			}
		
			public String getRight() {
				return Right;
			}
		
			public void setRight(String value) {
				String old = Right;
				Right = value;
				firePropertyChange("Right", old, Right);
			}
		
			public IUi2DAnimation getRightObject() {				
				return RightObject;
			}
		
			public void setRightObject(IUi2DAnimation value) {
				IUi2DAnimation old = RightObject;
				RightObject = value;
				firePropertyChange("RightObject", old, RightObject);
			}
		
			public String getRightBottom() {
				return RightBottom;
			}
		
			public void setRightBottom(String value) {
				String old = RightBottom;
				RightBottom = value;
				firePropertyChange("RightBottom", old, RightBottom);
			}
		
			public IUi2DAnimation getRightBottomObject() {				
				return RightBottomObject;
			}
		
			public void setRightBottomObject(IUi2DAnimation value) {
				IUi2DAnimation old = RightBottomObject;
				RightBottomObject = value;
				firePropertyChange("RightBottomObject", old, RightBottomObject);
			}
		
			public String getBottomRight() {
				return BottomRight;
			}
		
			public void setBottomRight(String value) {
				String old = BottomRight;
				BottomRight = value;
				firePropertyChange("BottomRight", old, BottomRight);
			}
		
			public IUi2DAnimation getBottomRightObject() {				
				return BottomRightObject;
			}
		
			public void setBottomRightObject(IUi2DAnimation value) {
				IUi2DAnimation old = BottomRightObject;
				BottomRightObject = value;
				firePropertyChange("BottomRightObject", old, BottomRightObject);
			}
		
			public String getBottom() {
				return Bottom;
			}
		
			public void setBottom(String value) {
				String old = Bottom;
				Bottom = value;
				firePropertyChange("Bottom", old, Bottom);
			}
		
			public IUi2DAnimation getBottomObject() {				
				return BottomObject;
			}
		
			public void setBottomObject(IUi2DAnimation value) {
				IUi2DAnimation old = BottomObject;
				BottomObject = value;
				firePropertyChange("BottomObject", old, BottomObject);
			}
		
			public String getBottomLeft() {
				return BottomLeft;
			}
		
			public void setBottomLeft(String value) {
				String old = BottomLeft;
				BottomLeft = value;
				firePropertyChange("BottomLeft", old, BottomLeft);
			}
		
			public IUi2DAnimation getBottomLeftObject() {				
				return BottomLeftObject;
			}
		
			public void setBottomLeftObject(IUi2DAnimation value) {
				IUi2DAnimation old = BottomLeftObject;
				BottomLeftObject = value;
				firePropertyChange("BottomLeftObject", old, BottomLeftObject);
			}
		
			public String getLeftTop() {
				return LeftTop;
			}
		
			public void setLeftTop(String value) {
				String old = LeftTop;
				LeftTop = value;
				firePropertyChange("LeftTop", old, LeftTop);
			}
		
			public IUi2DAnimation getLeftTopObject() {				
				return LeftTopObject;
			}
		
			public void setLeftTopObject(IUi2DAnimation value) {
				IUi2DAnimation old = LeftTopObject;
				LeftTopObject = value;
				firePropertyChange("LeftTopObject", old, LeftTopObject);
			}
		
			public String getLeft() {
				return Left;
			}
		
			public void setLeft(String value) {
				String old = Left;
				Left = value;
				firePropertyChange("Left", old, Left);
			}
		
			public IUi2DAnimation getLeftObject() {				
				return LeftObject;
			}
		
			public void setLeftObject(IUi2DAnimation value) {
				IUi2DAnimation old = LeftObject;
				LeftObject = value;
				firePropertyChange("LeftObject", old, LeftObject);
			}
		
			public String getLeftBottom() {
				return LeftBottom;
			}
		
			public void setLeftBottom(String value) {
				String old = LeftBottom;
				LeftBottom = value;
				firePropertyChange("LeftBottom", old, LeftBottom);
			}
		
			public IUi2DAnimation getLeftBottomObject() {				
				return LeftBottomObject;
			}
		
			public void setLeftBottomObject(IUi2DAnimation value) {
				IUi2DAnimation old = LeftBottomObject;
				LeftBottomObject = value;
				firePropertyChange("LeftBottomObject", old, LeftBottomObject);
			}
		
			public String getMiddle() {
				return Middle;
			}
		
			public void setMiddle(String value) {
				String old = Middle;
				Middle = value;
				firePropertyChange("Middle", old, Middle);
			}
		
			public IUi2DAnimation getMiddleObject() {				
				return MiddleObject;
			}
		
			public void setMiddleObject(IUi2DAnimation value) {
				IUi2DAnimation old = MiddleObject;
				MiddleObject = value;
				firePropertyChange("MiddleObject", old, MiddleObject);
			}
		
			public int getOverlapLeft() {
				return OverlapLeft;
			}
		
			public void setOverlapLeft(int value) {
				int old = OverlapLeft;
				OverlapLeft = value;
				firePropertyChange("OverlapLeft", old, OverlapLeft);
			}
		
			public int getOverlapTop() {
				return OverlapTop;
			}
		
			public void setOverlapTop(int value) {
				int old = OverlapTop;
				OverlapTop = value;
				firePropertyChange("OverlapTop", old, OverlapTop);
			}
		
			public int getOverlapRight() {
				return OverlapRight;
			}
		
			public void setOverlapRight(int value) {
				int old = OverlapRight;
				OverlapRight = value;
				firePropertyChange("OverlapRight", old, OverlapRight);
			}
		
			public int getOverlapBottom() {
				return OverlapBottom;
			}
		
			public void setOverlapBottom(int value) {
				int old = OverlapBottom;
				OverlapBottom = value;
				firePropertyChange("OverlapBottom", old, OverlapBottom);
			}
		
			}
		