
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IGaugeDrawTemplate;
			import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQGaugeDrawTemplate extends EQClass implements IGaugeDrawTemplate {
					private String Background;
	private IUi2DAnimation BackgroundObject;
	private String Fill;
	private IUi2DAnimation FillObject;
	private String Lines;
	private IUi2DAnimation LinesObject;
	private String LinesFill;
	private IUi2DAnimation LinesFillObject;
	private String EndCapRight;
	private IUi2DAnimation EndCapRightObject;
	private String EndCapLeft;
	private IUi2DAnimation EndCapLeftObject;

				
				
			public String getBackground() {
				return Background;
			}
		
			public void setBackground(String value) {
				String old = Background;
				Background = value;
				firePropertyChange("Background", old, Background);
			}
		
			public IUi2DAnimation getBackgroundObject() {				
				return BackgroundObject;
			}
		
			public void setBackgroundObject(IUi2DAnimation value) {
				IUi2DAnimation old = BackgroundObject;
				BackgroundObject = value;
				firePropertyChange("BackgroundObject", old, BackgroundObject);
			}
		
			public String getFill() {
				return Fill;
			}
		
			public void setFill(String value) {
				String old = Fill;
				Fill = value;
				firePropertyChange("Fill", old, Fill);
			}
		
			public IUi2DAnimation getFillObject() {				
				return FillObject;
			}
		
			public void setFillObject(IUi2DAnimation value) {
				IUi2DAnimation old = FillObject;
				FillObject = value;
				firePropertyChange("FillObject", old, FillObject);
			}
		
			public String getLines() {
				return Lines;
			}
		
			public void setLines(String value) {
				String old = Lines;
				Lines = value;
				firePropertyChange("Lines", old, Lines);
			}
		
			public IUi2DAnimation getLinesObject() {				
				return LinesObject;
			}
		
			public void setLinesObject(IUi2DAnimation value) {
				IUi2DAnimation old = LinesObject;
				LinesObject = value;
				firePropertyChange("LinesObject", old, LinesObject);
			}
		
			public String getLinesFill() {
				return LinesFill;
			}
		
			public void setLinesFill(String value) {
				String old = LinesFill;
				LinesFill = value;
				firePropertyChange("LinesFill", old, LinesFill);
			}
		
			public IUi2DAnimation getLinesFillObject() {				
				return LinesFillObject;
			}
		
			public void setLinesFillObject(IUi2DAnimation value) {
				IUi2DAnimation old = LinesFillObject;
				LinesFillObject = value;
				firePropertyChange("LinesFillObject", old, LinesFillObject);
			}
		
			public String getEndCapRight() {
				return EndCapRight;
			}
		
			public void setEndCapRight(String value) {
				String old = EndCapRight;
				EndCapRight = value;
				firePropertyChange("EndCapRight", old, EndCapRight);
			}
		
			public IUi2DAnimation getEndCapRightObject() {				
				return EndCapRightObject;
			}
		
			public void setEndCapRightObject(IUi2DAnimation value) {
				IUi2DAnimation old = EndCapRightObject;
				EndCapRightObject = value;
				firePropertyChange("EndCapRightObject", old, EndCapRightObject);
			}
		
			public String getEndCapLeft() {
				return EndCapLeft;
			}
		
			public void setEndCapLeft(String value) {
				String old = EndCapLeft;
				EndCapLeft = value;
				firePropertyChange("EndCapLeft", old, EndCapLeft);
			}
		
			public IUi2DAnimation getEndCapLeftObject() {				
				return EndCapLeftObject;
			}
		
			public void setEndCapLeftObject(IUi2DAnimation value) {
				IUi2DAnimation old = EndCapLeftObject;
				EndCapLeftObject = value;
				firePropertyChange("EndCapLeftObject", old, EndCapLeftObject);
			}
		
			}
		