
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IGauge;
			import com.barbre.fiddle.elements.IGaugeDrawTemplate;import com.barbre.fiddle.elements.IRGB;import com.barbre.fiddle.elements.IRGB;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQGauge extends EQControl implements IGauge {
					private IGaugeDrawTemplate GaugeDrawTemplate;
	private int EQType;
	private IRGB FillTint;
	private boolean DrawLinesFill;
	private IRGB LinesFillTint;
	private int TextOffsetX;
	private int TextOffsetY;
	private int GaugeOffsetX;
	private int GaugeOffsetY;

				
				
			public IGaugeDrawTemplate getGaugeDrawTemplate() {
				return GaugeDrawTemplate;
			}
		
			public void setGaugeDrawTemplate(IGaugeDrawTemplate value) {
				IGaugeDrawTemplate old = GaugeDrawTemplate;
				GaugeDrawTemplate = value;
				firePropertyChange("GaugeDrawTemplate", old, GaugeDrawTemplate);
			}
		
			public int getEQType() {
				return EQType;
			}
		
			public void setEQType(int value) {
				int old = EQType;
				EQType = value;
				firePropertyChange("EQType", old, EQType);
			}
		
			public IRGB getFillTint() {
				return FillTint;
			}
		
			public void setFillTint(IRGB value) {
				IRGB old = FillTint;
				FillTint = value;
				firePropertyChange("FillTint", old, FillTint);
			}
		
			public boolean getDrawLinesFill() {
				return DrawLinesFill;
			}
		
			public void setDrawLinesFill(boolean value) {
				boolean old = DrawLinesFill;
				DrawLinesFill = value;
				firePropertyChange("DrawLinesFill", old, DrawLinesFill);
			}
		
			public IRGB getLinesFillTint() {
				return LinesFillTint;
			}
		
			public void setLinesFillTint(IRGB value) {
				IRGB old = LinesFillTint;
				LinesFillTint = value;
				firePropertyChange("LinesFillTint", old, LinesFillTint);
			}
		
			public int getTextOffsetX() {
				return TextOffsetX;
			}
		
			public void setTextOffsetX(int value) {
				int old = TextOffsetX;
				TextOffsetX = value;
				firePropertyChange("TextOffsetX", old, TextOffsetX);
			}
		
			public int getTextOffsetY() {
				return TextOffsetY;
			}
		
			public void setTextOffsetY(int value) {
				int old = TextOffsetY;
				TextOffsetY = value;
				firePropertyChange("TextOffsetY", old, TextOffsetY);
			}
		
			public int getGaugeOffsetX() {
				return GaugeOffsetX;
			}
		
			public void setGaugeOffsetX(int value) {
				int old = GaugeOffsetX;
				GaugeOffsetX = value;
				firePropertyChange("GaugeOffsetX", old, GaugeOffsetX);
			}
		
			public int getGaugeOffsetY() {
				return GaugeOffsetY;
			}
		
			public void setGaugeOffsetY(int value) {
				int old = GaugeOffsetY;
				GaugeOffsetY = value;
				firePropertyChange("GaugeOffsetY", old, GaugeOffsetY);
			}
		
			}
		