
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IInvSlot;
			import com.barbre.fiddle.elements.IUi2DAnimation;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQInvSlot extends EQControl implements IInvSlot {
					private int EQType;
	private String Background;
	private IUi2DAnimation BackgroundObject;
	private int ItemOffsetX;
	private int ItemOffsetY;

				
				
			public int getEQType() {
				return EQType;
			}
		
			public void setEQType(int value) {
				int old = EQType;
				EQType = value;
				firePropertyChange("EQType", old, EQType);
			}
		
			public String getBackground() {
				return Background;
			}
		
			public void setBackground(String value) {
				String old = Background;
				Background = value;
				firePropertyChange("Background", old, Background);
			}
		
			public IUi2DAnimation getBackgroundObject() {				
				return BackgroundObject;
			}
		
			public void setBackgroundObject(IUi2DAnimation value) {
				IUi2DAnimation old = BackgroundObject;
				BackgroundObject = value;
				firePropertyChange("BackgroundObject", old, BackgroundObject);
			}
		
			public int getItemOffsetX() {
				return ItemOffsetX;
			}
		
			public void setItemOffsetX(int value) {
				int old = ItemOffsetX;
				ItemOffsetX = value;
				firePropertyChange("ItemOffsetX", old, ItemOffsetX);
			}
		
			public int getItemOffsetY() {
				return ItemOffsetY;
			}
		
			public void setItemOffsetY(int value) {
				int old = ItemOffsetY;
				ItemOffsetY = value;
				firePropertyChange("ItemOffsetY", old, ItemOffsetY);
			}
		
			}
		