
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.ILabel;
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQLabel extends EQControl implements ILabel {
					private int EQType;
	private boolean NoWrap;
	private boolean AlignCenter;
	private boolean AlignRight;

				
				
			public int getEQType() {
				return EQType;
			}
		
			public void setEQType(int value) {
				int old = EQType;
				EQType = value;
				firePropertyChange("EQType", old, EQType);
			}
		
			public boolean getNoWrap() {
				return NoWrap;
			}
		
			public void setNoWrap(boolean value) {
				boolean old = NoWrap;
				NoWrap = value;
				firePropertyChange("NoWrap", old, NoWrap);
			}
		
			public boolean getAlignCenter() {
				return AlignCenter;
			}
		
			public void setAlignCenter(boolean value) {
				boolean old = AlignCenter;
				AlignCenter = value;
				firePropertyChange("AlignCenter", old, AlignCenter);
			}
		
			public boolean getAlignRight() {
				return AlignRight;
			}
		
			public void setAlignRight(boolean value) {
				boolean old = AlignRight;
				AlignRight = value;
				firePropertyChange("AlignRight", old, AlignRight);
			}
		
			}
		