
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IListbox;
			import com.barbre.fiddle.elements.IListboxColumn;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQListbox extends EQControl implements IListbox {
					private IListboxColumn[] Columns;
	private boolean OwnerDraw;

				
				
			public IListboxColumn[] getColumns() {
				return Columns;
			}
		
			public void setColumns(IListboxColumn[] value) {
				IListboxColumn[] old = Columns;
				Columns = value;
				firePropertyChange("Columns", old, Columns);
			}
		
			public IListboxColumn getColumns(int index) {
				return Columns[index];
			}
		
			public void setColumns(int index, IListboxColumn value) {
				IListboxColumn[] old = Columns;
				Columns[index] = value;
				firePropertyChange("Columns", old, Columns);
			}
		
			public boolean getOwnerDraw() {
				return OwnerDraw;
			}
		
			public void setOwnerDraw(boolean value) {
				boolean old = OwnerDraw;
				OwnerDraw = value;
				firePropertyChange("OwnerDraw", old, OwnerDraw);
			}
		
			}
		