
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IPage;
			import com.barbre.fiddle.elements.IRGB;import com.barbre.fiddle.elements.IRGB;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IScreenPiece;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQPage extends EQControl implements IPage {
					private String TabText;
	private IRGB TabTextColor;
	private IRGB TabTextActiveColor;
	private String TabIcon;
	private IUi2DAnimation TabIconObject;
	private String TabIconActive;
	private IUi2DAnimation TabIconActiveObject;
	private String[] Pieces;
	private IScreenPiece[] PiecesObject;

				
				
			public String getTabText() {
				return TabText;
			}
		
			public void setTabText(String value) {
				String old = TabText;
				TabText = value;
				firePropertyChange("TabText", old, TabText);
			}
		
			public IRGB getTabTextColor() {
				return TabTextColor;
			}
		
			public void setTabTextColor(IRGB value) {
				IRGB old = TabTextColor;
				TabTextColor = value;
				firePropertyChange("TabTextColor", old, TabTextColor);
			}
		
			public IRGB getTabTextActiveColor() {
				return TabTextActiveColor;
			}
		
			public void setTabTextActiveColor(IRGB value) {
				IRGB old = TabTextActiveColor;
				TabTextActiveColor = value;
				firePropertyChange("TabTextActiveColor", old, TabTextActiveColor);
			}
		
			public String getTabIcon() {
				return TabIcon;
			}
		
			public void setTabIcon(String value) {
				String old = TabIcon;
				TabIcon = value;
				firePropertyChange("TabIcon", old, TabIcon);
			}
		
			public IUi2DAnimation getTabIconObject() {				
				return TabIconObject;
			}
		
			public void setTabIconObject(IUi2DAnimation value) {
				IUi2DAnimation old = TabIconObject;
				TabIconObject = value;
				firePropertyChange("TabIconObject", old, TabIconObject);
			}
		
			public String getTabIconActive() {
				return TabIconActive;
			}
		
			public void setTabIconActive(String value) {
				String old = TabIconActive;
				TabIconActive = value;
				firePropertyChange("TabIconActive", old, TabIconActive);
			}
		
			public IUi2DAnimation getTabIconActiveObject() {				
				return TabIconActiveObject;
			}
		
			public void setTabIconActiveObject(IUi2DAnimation value) {
				IUi2DAnimation old = TabIconActiveObject;
				TabIconActiveObject = value;
				firePropertyChange("TabIconActiveObject", old, TabIconActiveObject);
			}
		
			public String[] getPieces() {
				return Pieces;
			}
		
			public void setPieces(String[] value) {
				String[] old = Pieces;
				Pieces = value;
				firePropertyChange("Pieces", old, Pieces);
			}
		
			public String getPieces(int index) {
				return Pieces[index];
			}
		
			public void setPieces(int index, String value) {
				String[] old = Pieces;
				Pieces[index] = value;
				firePropertyChange("Pieces", old, Pieces);
			}
		
			public IScreenPiece[] getPiecesObject() {				
				return PiecesObject;
			}
		
			public void setPiecesObject(IScreenPiece[] value) {
				IScreenPiece[] old = PiecesObject;
				PiecesObject = value;
				firePropertyChange("PiecesObject", old, PiecesObject);
			}
		
			public IScreenPiece getPiecesObject(int index) {
				return PiecesObject[index];
			}
		
			public void setPiecesObject(int index, IScreenPiece value) {
				IScreenPiece[] old = PiecesObject;
				PiecesObject[index] = value;
				firePropertyChange("PiecesObject", old, PiecesObject);
			}
		
			}
		