
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IPoint;
			
	import java.awt.Point;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQPoint extends EQNode implements IPoint {
					private int X;
	private int Y;

				
				
			public int getX() {
				return X;
			}
		
			public void setX(int value) {
				int old = X;
				X = value;
				firePropertyChange("X", old, X);
			}
		
			public int getY() {
				return Y;
			}
		
			public void setY(int value) {
				int old = Y;
				Y = value;
				firePropertyChange("Y", old, Y);
			}
		
	
			public Point getPoint() {
				return new Point(getX(), getY());
			}
		
	
			public void setPoint(Point p) {
				setX(p.x);
				setY(p.y);
			}
		
			}
		