
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IRGB;
			
	import java.awt.Color;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQRGB extends EQClass implements IRGB {
							private int Alpha = 255;
				private int R = 0;
				private int G = 0;
				private int B = 0;

				
				
			public int getAlpha() {
				return Alpha;
			}
		
			public void setAlpha(int value) {
				int old = Alpha;
				Alpha = value;
				firePropertyChange("Alpha", old, Alpha);
			}
		
			public int getR() {
				return R;
			}
		
			public void setR(int value) {
				int old = R;
				R = value;
				firePropertyChange("R", old, R);
			}
		
			public int getG() {
				return G;
			}
		
			public void setG(int value) {
				int old = G;
				G = value;
				firePropertyChange("G", old, G);
			}
		
			public int getB() {
				return B;
			}
		
			public void setB(int value) {
				int old = B;
				B = value;
				firePropertyChange("B", old, B);
			}
		
	
			public Color getColor() {
				return new Color(getR(), getG(), getB(), getAlpha());
			}
		
	
			public void setColor(Color c) {
				setAlpha(c.getAlpha());
				setR(c.getRed());
				setG(c.getGreen());
				setB(c.getBlue());
			}
		
			}
		