package com.barbre.fiddle.io;

import com.barbre.fiddle.elements.IScreen;
import com.barbre.fiddle.elements.IScreenPiece;
import com.barbre44.util.Debug;

/**
 * Generated by BeanBuilder for SIDL Fiddle
 */
public class EQScreen extends EQControl implements IScreen {
	private boolean Style_Titlebar;
	private boolean Style_Closebox;
	private boolean Style_Minimizebox;
	private boolean Style_Sizable;
	private String[] Pieces;
	private IScreenPiece[] PiecesObject;

	public boolean getStyle_Titlebar() {
		return Style_Titlebar;
	}

	public void setStyle_Titlebar(boolean value) {
		boolean old = Style_Titlebar;
		Style_Titlebar = value;
		firePropertyChange("Style_Titlebar", old, Style_Titlebar);
	}

	public boolean getStyle_Closebox() {
		return Style_Closebox;
	}

	public void setStyle_Closebox(boolean value) {
		boolean old = Style_Closebox;
		Style_Closebox = value;
		firePropertyChange("Style_Closebox", old, Style_Closebox);
	}

	public boolean getStyle_Minimizebox() {
		return Style_Minimizebox;
	}

	public void setStyle_Minimizebox(boolean value) {
		boolean old = Style_Minimizebox;
		Style_Minimizebox = value;
		firePropertyChange("Style_Minimizebox", old, Style_Minimizebox);
	}

	public boolean getStyle_Sizable() {
		return Style_Sizable;
	}

	public void setStyle_Sizable(boolean value) {
		boolean old = Style_Sizable;
		Style_Sizable = value;
		firePropertyChange("Style_Sizable", old, Style_Sizable);
	}

	public String[] getPieces() {
		return Pieces;
	}

	public void setPieces(String[] value) {
		String[] old = Pieces;
		Pieces = value;
		firePropertyChange("Pieces", old, Pieces);
	}

	public String getPieces(int index) {
		return Pieces[index];
	}

	public void setPieces(int index, String value) {
		String[] old = Pieces;
		Pieces[index] = value;
		firePropertyChange("Pieces", old, Pieces);
	}

	public IScreenPiece[] getPiecesObject() {
		return PiecesObject;
	}

	public void setPiecesObject(IScreenPiece[] value) {
		Debug.println(this, "value="+value);
		IScreenPiece[] old = PiecesObject;
		PiecesObject = value;
		firePropertyChange("PiecesObject", old, PiecesObject);
	}

	public IScreenPiece getPiecesObject(int index) {
		return PiecesObject[index];
	}

	public void setPiecesObject(int index, IScreenPiece value) {
		IScreenPiece[] old = PiecesObject;
		PiecesObject[index] = value;
		firePropertyChange("PiecesObject", old, PiecesObject);
	}

}