
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.ISliderDrawTemplate;
			import com.barbre.fiddle.elements.IButtonDrawTemplate;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQSliderDrawTemplate extends EQClass implements ISliderDrawTemplate {
					private IButtonDrawTemplate Thumb;
	private String Background;
	private IUi2DAnimation BackgroundObject;
	private String EndCapRight;
	private IUi2DAnimation EndCapRightObject;
	private String EndCapLeft;
	private IUi2DAnimation EndCapLeftObject;

				
				
			public IButtonDrawTemplate getThumb() {
				return Thumb;
			}
		
			public void setThumb(IButtonDrawTemplate value) {
				IButtonDrawTemplate old = Thumb;
				Thumb = value;
				firePropertyChange("Thumb", old, Thumb);
			}
		
			public String getBackground() {
				return Background;
			}
		
			public void setBackground(String value) {
				String old = Background;
				Background = value;
				firePropertyChange("Background", old, Background);
			}
		
			public IUi2DAnimation getBackgroundObject() {				
				return BackgroundObject;
			}
		
			public void setBackgroundObject(IUi2DAnimation value) {
				IUi2DAnimation old = BackgroundObject;
				BackgroundObject = value;
				firePropertyChange("BackgroundObject", old, BackgroundObject);
			}
		
			public String getEndCapRight() {
				return EndCapRight;
			}
		
			public void setEndCapRight(String value) {
				String old = EndCapRight;
				EndCapRight = value;
				firePropertyChange("EndCapRight", old, EndCapRight);
			}
		
			public IUi2DAnimation getEndCapRightObject() {				
				return EndCapRightObject;
			}
		
			public void setEndCapRightObject(IUi2DAnimation value) {
				IUi2DAnimation old = EndCapRightObject;
				EndCapRightObject = value;
				firePropertyChange("EndCapRightObject", old, EndCapRightObject);
			}
		
			public String getEndCapLeft() {
				return EndCapLeft;
			}
		
			public void setEndCapLeft(String value) {
				String old = EndCapLeft;
				EndCapLeft = value;
				firePropertyChange("EndCapLeft", old, EndCapLeft);
			}
		
			public IUi2DAnimation getEndCapLeftObject() {				
				return EndCapLeftObject;
			}
		
			public void setEndCapLeftObject(IUi2DAnimation value) {
				IUi2DAnimation old = EndCapLeftObject;
				EndCapLeftObject = value;
				firePropertyChange("EndCapLeftObject", old, EndCapLeftObject);
			}
		
			}
		