
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.ISlider;
			import com.barbre.fiddle.elements.ISliderDrawTemplate;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQSlider extends EQControl implements ISlider {
					private String SliderArt;
	private ISliderDrawTemplate SliderArtObject;

				
				
			public String getSliderArt() {
				return SliderArt;
			}
		
			public void setSliderArt(String value) {
				String old = SliderArt;
				SliderArt = value;
				firePropertyChange("SliderArt", old, SliderArt);
			}
		
			public ISliderDrawTemplate getSliderArtObject() {				
				return SliderArtObject;
			}
		
			public void setSliderArtObject(ISliderDrawTemplate value) {
				ISliderDrawTemplate old = SliderArtObject;
				SliderArtObject = value;
				firePropertyChange("SliderArtObject", old, SliderArtObject);
			}
		
			}
		