
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.ISpellGemDrawTemplate;
			import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQSpellGemDrawTemplate extends EQClass implements ISpellGemDrawTemplate {
					private String Holder;
	private IUi2DAnimation HolderObject;
	private String Background;
	private IUi2DAnimation BackgroundObject;
	private String Highlight;
	private IUi2DAnimation HighlightObject;

				
				
			public String getHolder() {
				return Holder;
			}
		
			public void setHolder(String value) {
				String old = Holder;
				Holder = value;
				firePropertyChange("Holder", old, Holder);
			}
		
			public IUi2DAnimation getHolderObject() {				
				return HolderObject;
			}
		
			public void setHolderObject(IUi2DAnimation value) {
				IUi2DAnimation old = HolderObject;
				HolderObject = value;
				firePropertyChange("HolderObject", old, HolderObject);
			}
		
			public String getBackground() {
				return Background;
			}
		
			public void setBackground(String value) {
				String old = Background;
				Background = value;
				firePropertyChange("Background", old, Background);
			}
		
			public IUi2DAnimation getBackgroundObject() {				
				return BackgroundObject;
			}
		
			public void setBackgroundObject(IUi2DAnimation value) {
				IUi2DAnimation old = BackgroundObject;
				BackgroundObject = value;
				firePropertyChange("BackgroundObject", old, BackgroundObject);
			}
		
			public String getHighlight() {
				return Highlight;
			}
		
			public void setHighlight(String value) {
				String old = Highlight;
				Highlight = value;
				firePropertyChange("Highlight", old, Highlight);
			}
		
			public IUi2DAnimation getHighlightObject() {				
				return HighlightObject;
			}
		
			public void setHighlightObject(IUi2DAnimation value) {
				IUi2DAnimation old = HighlightObject;
				HighlightObject = value;
				firePropertyChange("HighlightObject", old, HighlightObject);
			}
		
			}
		