
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IStaticText;
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQStaticText extends EQStaticScreenPiece implements IStaticText {
					private boolean NoWrap;
	private boolean AlignCenter;
	private boolean AlignRight;

				
				
			public boolean getNoWrap() {
				return NoWrap;
			}
		
			public void setNoWrap(boolean value) {
				boolean old = NoWrap;
				NoWrap = value;
				firePropertyChange("NoWrap", old, NoWrap);
			}
		
			public boolean getAlignCenter() {
				return AlignCenter;
			}
		
			public void setAlignCenter(boolean value) {
				boolean old = AlignCenter;
				AlignCenter = value;
				firePropertyChange("AlignCenter", old, AlignCenter);
			}
		
			public boolean getAlignRight() {
				return AlignRight;
			}
		
			public void setAlignRight(boolean value) {
				boolean old = AlignRight;
				AlignRight = value;
				firePropertyChange("AlignRight", old, AlignRight);
			}
		
			}
		