
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IStaticScreenPiece;
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQStaticScreenPiece extends EQScreenPiece implements IStaticScreenPiece {
					private boolean AutoDraw;

				
				
			public boolean getAutoDraw() {
				return AutoDraw;
			}
		
			public void setAutoDraw(boolean value) {
				boolean old = AutoDraw;
				AutoDraw = value;
				firePropertyChange("AutoDraw", old, AutoDraw);
			}
		
			}
		