
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IStaticAnimation;
			import com.barbre.fiddle.elements.IUi2DAnimation;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQStaticAnimation extends EQStaticScreenPiece implements IStaticAnimation {
					private String Animation;
	private IUi2DAnimation AnimationObject;

				
				
			public String getAnimation() {
				return Animation;
			}
		
			public void setAnimation(String value) {
				String old = Animation;
				Animation = value;
				firePropertyChange("Animation", old, Animation);
			}
		
			public IUi2DAnimation getAnimationObject() {				
				return AnimationObject;
			}
		
			public void setAnimationObject(IUi2DAnimation value) {
				IUi2DAnimation old = AnimationObject;
				AnimationObject = value;
				firePropertyChange("AnimationObject", old, AnimationObject);
			}
		
			}
		