
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IStaticHeader;
			import com.barbre.fiddle.elements.IFrameTemplate;import com.barbre.fiddle.elements.IRGB;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQStaticHeader extends EQStaticScreenPiece implements IStaticHeader {
					private String FrameTemplate;
	private IFrameTemplate FrameTemplateObject;
	private String TextReference;
	private IRGB TextColor;

				
				
			public String getFrameTemplate() {
				return FrameTemplate;
			}
		
			public void setFrameTemplate(String value) {
				String old = FrameTemplate;
				FrameTemplate = value;
				firePropertyChange("FrameTemplate", old, FrameTemplate);
			}
		
			public IFrameTemplate getFrameTemplateObject() {				
				return FrameTemplateObject;
			}
		
			public void setFrameTemplateObject(IFrameTemplate value) {
				IFrameTemplate old = FrameTemplateObject;
				FrameTemplateObject = value;
				firePropertyChange("FrameTemplateObject", old, FrameTemplateObject);
			}
		
			public String getTextReference() {
				return TextReference;
			}
		
			public void setTextReference(String value) {
				String old = TextReference;
				TextReference = value;
				firePropertyChange("TextReference", old, TextReference);
			}
		
			public IRGB getTextColor() {
				return TextColor;
			}
		
			public void setTextColor(IRGB value) {
				IRGB old = TextColor;
				TextColor = value;
				firePropertyChange("TextColor", old, TextColor);
			}
		
			}
		