
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.ISTMLbox;
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQSTMLbox extends EQControl implements ISTMLbox {
				
				
				
			}
		