
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.ISuiteDefaults;
			import com.barbre.fiddle.elements.IWindowDrawTemplate;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;import com.barbre.fiddle.elements.IUi2DAnimation;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQSuiteDefaults extends EQClass implements ISuiteDefaults {
					private String DefaultWindowDrawTemplate;
	private IWindowDrawTemplate DefaultWindowDrawTemplateObject;
	private String CursorDefault;
	private IUi2DAnimation CursorDefaultObject;
	private String CursorResizeNS;
	private IUi2DAnimation CursorResizeNSObject;
	private String CursorResizeEW;
	private IUi2DAnimation CursorResizeEWObject;
	private String CursorResizeNESW;
	private IUi2DAnimation CursorResizeNESWObject;
	private String CursorResizeNWSE;
	private IUi2DAnimation CursorResizeNWSEObject;
	private String CursorDrag;
	private IUi2DAnimation CursorDragObject;

				
				
			public String getDefaultWindowDrawTemplate() {
				return DefaultWindowDrawTemplate;
			}
		
			public void setDefaultWindowDrawTemplate(String value) {
				String old = DefaultWindowDrawTemplate;
				DefaultWindowDrawTemplate = value;
				firePropertyChange("DefaultWindowDrawTemplate", old, DefaultWindowDrawTemplate);
			}
		
			public IWindowDrawTemplate getDefaultWindowDrawTemplateObject() {				
				return DefaultWindowDrawTemplateObject;
			}
		
			public void setDefaultWindowDrawTemplateObject(IWindowDrawTemplate value) {
				IWindowDrawTemplate old = DefaultWindowDrawTemplateObject;
				DefaultWindowDrawTemplateObject = value;
				firePropertyChange("DefaultWindowDrawTemplateObject", old, DefaultWindowDrawTemplateObject);
			}
		
			public String getCursorDefault() {
				return CursorDefault;
			}
		
			public void setCursorDefault(String value) {
				String old = CursorDefault;
				CursorDefault = value;
				firePropertyChange("CursorDefault", old, CursorDefault);
			}
		
			public IUi2DAnimation getCursorDefaultObject() {				
				return CursorDefaultObject;
			}
		
			public void setCursorDefaultObject(IUi2DAnimation value) {
				IUi2DAnimation old = CursorDefaultObject;
				CursorDefaultObject = value;
				firePropertyChange("CursorDefaultObject", old, CursorDefaultObject);
			}
		
			public String getCursorResizeNS() {
				return CursorResizeNS;
			}
		
			public void setCursorResizeNS(String value) {
				String old = CursorResizeNS;
				CursorResizeNS = value;
				firePropertyChange("CursorResizeNS", old, CursorResizeNS);
			}
		
			public IUi2DAnimation getCursorResizeNSObject() {				
				return CursorResizeNSObject;
			}
		
			public void setCursorResizeNSObject(IUi2DAnimation value) {
				IUi2DAnimation old = CursorResizeNSObject;
				CursorResizeNSObject = value;
				firePropertyChange("CursorResizeNSObject", old, CursorResizeNSObject);
			}
		
			public String getCursorResizeEW() {
				return CursorResizeEW;
			}
		
			public void setCursorResizeEW(String value) {
				String old = CursorResizeEW;
				CursorResizeEW = value;
				firePropertyChange("CursorResizeEW", old, CursorResizeEW);
			}
		
			public IUi2DAnimation getCursorResizeEWObject() {				
				return CursorResizeEWObject;
			}
		
			public void setCursorResizeEWObject(IUi2DAnimation value) {
				IUi2DAnimation old = CursorResizeEWObject;
				CursorResizeEWObject = value;
				firePropertyChange("CursorResizeEWObject", old, CursorResizeEWObject);
			}
		
			public String getCursorResizeNESW() {
				return CursorResizeNESW;
			}
		
			public void setCursorResizeNESW(String value) {
				String old = CursorResizeNESW;
				CursorResizeNESW = value;
				firePropertyChange("CursorResizeNESW", old, CursorResizeNESW);
			}
		
			public IUi2DAnimation getCursorResizeNESWObject() {				
				return CursorResizeNESWObject;
			}
		
			public void setCursorResizeNESWObject(IUi2DAnimation value) {
				IUi2DAnimation old = CursorResizeNESWObject;
				CursorResizeNESWObject = value;
				firePropertyChange("CursorResizeNESWObject", old, CursorResizeNESWObject);
			}
		
			public String getCursorResizeNWSE() {
				return CursorResizeNWSE;
			}
		
			public void setCursorResizeNWSE(String value) {
				String old = CursorResizeNWSE;
				CursorResizeNWSE = value;
				firePropertyChange("CursorResizeNWSE", old, CursorResizeNWSE);
			}
		
			public IUi2DAnimation getCursorResizeNWSEObject() {				
				return CursorResizeNWSEObject;
			}
		
			public void setCursorResizeNWSEObject(IUi2DAnimation value) {
				IUi2DAnimation old = CursorResizeNWSEObject;
				CursorResizeNWSEObject = value;
				firePropertyChange("CursorResizeNWSEObject", old, CursorResizeNWSEObject);
			}
		
			public String getCursorDrag() {
				return CursorDrag;
			}
		
			public void setCursorDrag(String value) {
				String old = CursorDrag;
				CursorDrag = value;
				firePropertyChange("CursorDrag", old, CursorDrag);
			}
		
			public IUi2DAnimation getCursorDragObject() {				
				return CursorDragObject;
			}
		
			public void setCursorDragObject(IUi2DAnimation value) {
				IUi2DAnimation old = CursorDragObject;
				CursorDragObject = value;
				firePropertyChange("CursorDragObject", old, CursorDragObject);
			}
		
			}
		