package com.barbre.fiddle.io;

import com.barbre.fiddle.elements.IUi2DAnimation;
import com.barbre.fiddle.elements.IFrame;

/**
 * Generated by BeanBuilder for SIDL Fiddle
 */
public class EQUi2DAnimation extends EQClass implements IUi2DAnimation {
	private boolean Cycle;
	private boolean Grid;
	private boolean Vertical;
	private int CellWidth;
	private int CellHeight;
	private IFrame[] Frames;

	public boolean getCycle() {
		return Cycle;
	}

	public void setCycle(boolean value) {
		boolean old = Cycle;
		Cycle = value;
		firePropertyChange("Cycle", old, Cycle);
	}

	public boolean getGrid() {
		return Grid;
	}

	public void setGrid(boolean value) {
		boolean old = Grid;
		Grid = value;
		firePropertyChange("Grid", old, Grid);
	}

	public boolean getVertical() {
		return Vertical;
	}

	public void setVertical(boolean value) {
		boolean old = Vertical;
		Vertical = value;
		firePropertyChange("Vertical", old, Vertical);
	}

	public int getCellWidth() {
		return CellWidth;
	}

	public void setCellWidth(int value) {
		int old = CellWidth;
		CellWidth = value;
		firePropertyChange("CellWidth", old, CellWidth);
	}

	public int getCellHeight() {
		return CellHeight;
	}

	public void setCellHeight(int value) {
		int old = CellHeight;
		CellHeight = value;
		firePropertyChange("CellHeight", old, CellHeight);
	}

	public IFrame[] getFrames() {
		return Frames;
	}

	public void setFrames(IFrame[] value) {
		IFrame[] old = Frames;
		Frames = value;
		firePropertyChange("Frames", old, Frames);
	}

	public IFrame getFrames(int index) {
		return Frames[index];
	}

	public void setFrames(int index, IFrame value) {
		IFrame[] old = Frames;
		Frames[index] = value;
		firePropertyChange("Frames", old, Frames);
	}

}