
			package com.barbre.fiddle.io;
			
			import com.barbre.fiddle.elements.IWindowDrawTemplate;
			import com.barbre.fiddle.elements.ITextureInfo;import com.barbre.fiddle.elements.IScrollbarDrawTemplate;import com.barbre.fiddle.elements.IScrollbarDrawTemplate;import com.barbre.fiddle.elements.IButtonDrawTemplate;import com.barbre.fiddle.elements.IButtonDrawTemplate;import com.barbre.fiddle.elements.IButtonDrawTemplate;import com.barbre.fiddle.elements.IFrameTemplate;import com.barbre.fiddle.elements.IFrameTemplate;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public class EQWindowDrawTemplate extends EQClass implements IWindowDrawTemplate {
					private String Background;
	private ITextureInfo BackgroundObject;
	private IScrollbarDrawTemplate VSBTemplate;
	private IScrollbarDrawTemplate HSBTemplate;
	private IButtonDrawTemplate CloseBox;
	private IButtonDrawTemplate MinimizeBox;
	private IButtonDrawTemplate TileBox;
	private IFrameTemplate Border;
	private IFrameTemplate Titlebar;

				
				
			public String getBackground() {
				return Background;
			}
		
			public void setBackground(String value) {
				String old = Background;
				Background = value;
				firePropertyChange("Background", old, Background);
			}
		
			public ITextureInfo getBackgroundObject() {				
				return BackgroundObject;
			}
		
			public void setBackgroundObject(ITextureInfo value) {
				ITextureInfo old = BackgroundObject;
				BackgroundObject = value;
				firePropertyChange("BackgroundObject", old, BackgroundObject);
			}
		
			public IScrollbarDrawTemplate getVSBTemplate() {
				return VSBTemplate;
			}
		
			public void setVSBTemplate(IScrollbarDrawTemplate value) {
				IScrollbarDrawTemplate old = VSBTemplate;
				VSBTemplate = value;
				firePropertyChange("VSBTemplate", old, VSBTemplate);
			}
		
			public IScrollbarDrawTemplate getHSBTemplate() {
				return HSBTemplate;
			}
		
			public void setHSBTemplate(IScrollbarDrawTemplate value) {
				IScrollbarDrawTemplate old = HSBTemplate;
				HSBTemplate = value;
				firePropertyChange("HSBTemplate", old, HSBTemplate);
			}
		
			public IButtonDrawTemplate getCloseBox() {
				return CloseBox;
			}
		
			public void setCloseBox(IButtonDrawTemplate value) {
				IButtonDrawTemplate old = CloseBox;
				CloseBox = value;
				firePropertyChange("CloseBox", old, CloseBox);
			}
		
			public IButtonDrawTemplate getMinimizeBox() {
				return MinimizeBox;
			}
		
			public void setMinimizeBox(IButtonDrawTemplate value) {
				IButtonDrawTemplate old = MinimizeBox;
				MinimizeBox = value;
				firePropertyChange("MinimizeBox", old, MinimizeBox);
			}
		
			public IButtonDrawTemplate getTileBox() {
				return TileBox;
			}
		
			public void setTileBox(IButtonDrawTemplate value) {
				IButtonDrawTemplate old = TileBox;
				TileBox = value;
				firePropertyChange("TileBox", old, TileBox);
			}
		
			public IFrameTemplate getBorder() {
				return Border;
			}
		
			public void setBorder(IFrameTemplate value) {
				IFrameTemplate old = Border;
				Border = value;
				firePropertyChange("Border", old, Border);
			}
		
			public IFrameTemplate getTitlebar() {
				return Titlebar;
			}
		
			public void setTitlebar(IFrameTemplate value) {
				IFrameTemplate old = Titlebar;
				Titlebar = value;
				firePropertyChange("Titlebar", old, Titlebar);
			}
		
			}
		