
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IButton extends IControl {
				
			boolean getStyle_Checkbox();
		
			void setStyle_Checkbox(boolean value);
		
			String getRadioGroup();
		
			void setRadioGroup(String value);
		
			String getText();
		
			void setText(String value);
		
			IButtonDrawTemplate getButtonDrawTemplate();
		
			void setButtonDrawTemplate(IButtonDrawTemplate value);
		
			String getSoundPressed();
		
			void setSoundPressed(String value);
		
			String getSoundUp();
		
			void setSoundUp(String value);
		
			String getSoundFlyby();
		
			void setSoundFlyby(String value);
		
			IPoint getDecalOffset();
		
			void setDecalOffset(IPoint value);
		
			ISize getDecalSize();
		
			void setDecalSize(ISize value);
		
			}
		