
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IButtonDrawTemplate extends IClass {
				
			String getNormal();
		
			void setNormal(String value);
		
			IUi2DAnimation getNormalObject();
		
			void setNormalObject(IUi2DAnimation value);
		
			String getPressed();
		
			void setPressed(String value);
		
			IUi2DAnimation getPressedObject();
		
			void setPressedObject(IUi2DAnimation value);
		
			String getFlyby();
		
			void setFlyby(String value);
		
			IUi2DAnimation getFlybyObject();
		
			void setFlybyObject(IUi2DAnimation value);
		
			String getDisabled();
		
			void setDisabled(String value);
		
			IUi2DAnimation getDisabledObject();
		
			void setDisabledObject(IUi2DAnimation value);
		
			String getPressedFlyby();
		
			void setPressedFlyby(String value);
		
			IUi2DAnimation getPressedFlybyObject();
		
			void setPressedFlybyObject(IUi2DAnimation value);
		
			String getNormalDecal();
		
			void setNormalDecal(String value);
		
			IUi2DAnimation getNormalDecalObject();
		
			void setNormalDecalObject(IUi2DAnimation value);
		
			String getPressedDecal();
		
			void setPressedDecal(String value);
		
			IUi2DAnimation getPressedDecalObject();
		
			void setPressedDecalObject(IUi2DAnimation value);
		
			String getFlybyDecal();
		
			void setFlybyDecal(String value);
		
			IUi2DAnimation getFlybyDecalObject();
		
			void setFlybyDecalObject(IUi2DAnimation value);
		
			String getDisabledDecal();
		
			void setDisabledDecal(String value);
		
			IUi2DAnimation getDisabledDecalObject();
		
			void setDisabledDecalObject(IUi2DAnimation value);
		
			String getPressedFlybyDecal();
		
			void setPressedFlybyDecal(String value);
		
			IUi2DAnimation getPressedFlybyDecalObject();
		
			void setPressedFlybyDecalObject(IUi2DAnimation value);
		
			}
		