
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface ICombobox extends IControl {
				
			String getButton();
		
			void setButton(String value);
		
			IButtonDrawTemplate getButtonObject();
		
			void setButtonObject(IButtonDrawTemplate value);
		
			int getListHeight();
		
			void setListHeight(int value);
		
			String[] getChoices();
		
			void setChoices(String[] value);
		
			String getChoices(int index);
		
			void setChoices(int index, String value);
		
			}
		