
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IControl extends IScreenPiece {
				
			boolean getStyle_VScroll();
		
			void setStyle_VScroll(boolean value);
		
			boolean getStyle_HScroll();
		
			void setStyle_HScroll(boolean value);
		
			boolean getStyle_Transparent();
		
			void setStyle_Transparent(boolean value);
		
			boolean getStyle_Border();
		
			void setStyle_Border(boolean value);
		
			String getTooltipReference();
		
			void setTooltipReference(String value);
		
			String getDrawTemplate();
		
			void setDrawTemplate(String value);
		
			IWindowDrawTemplate getDrawTemplateObject();
		
			void setDrawTemplateObject(IWindowDrawTemplate value);
		
			}
		