
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IEditbox extends IControl {
				
			boolean getStyle_Multiline();
		
			void setStyle_Multiline(boolean value);
		
			}
		