
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IFrameTemplate extends IClass {
				
			String getTopLeft();
		
			void setTopLeft(String value);
		
			IUi2DAnimation getTopLeftObject();
		
			void setTopLeftObject(IUi2DAnimation value);
		
			String getTop();
		
			void setTop(String value);
		
			IUi2DAnimation getTopObject();
		
			void setTopObject(IUi2DAnimation value);
		
			String getTopRight();
		
			void setTopRight(String value);
		
			IUi2DAnimation getTopRightObject();
		
			void setTopRightObject(IUi2DAnimation value);
		
			String getRightTop();
		
			void setRightTop(String value);
		
			IUi2DAnimation getRightTopObject();
		
			void setRightTopObject(IUi2DAnimation value);
		
			String getRight();
		
			void setRight(String value);
		
			IUi2DAnimation getRightObject();
		
			void setRightObject(IUi2DAnimation value);
		
			String getRightBottom();
		
			void setRightBottom(String value);
		
			IUi2DAnimation getRightBottomObject();
		
			void setRightBottomObject(IUi2DAnimation value);
		
			String getBottomRight();
		
			void setBottomRight(String value);
		
			IUi2DAnimation getBottomRightObject();
		
			void setBottomRightObject(IUi2DAnimation value);
		
			String getBottom();
		
			void setBottom(String value);
		
			IUi2DAnimation getBottomObject();
		
			void setBottomObject(IUi2DAnimation value);
		
			String getBottomLeft();
		
			void setBottomLeft(String value);
		
			IUi2DAnimation getBottomLeftObject();
		
			void setBottomLeftObject(IUi2DAnimation value);
		
			String getLeftTop();
		
			void setLeftTop(String value);
		
			IUi2DAnimation getLeftTopObject();
		
			void setLeftTopObject(IUi2DAnimation value);
		
			String getLeft();
		
			void setLeft(String value);
		
			IUi2DAnimation getLeftObject();
		
			void setLeftObject(IUi2DAnimation value);
		
			String getLeftBottom();
		
			void setLeftBottom(String value);
		
			IUi2DAnimation getLeftBottomObject();
		
			void setLeftBottomObject(IUi2DAnimation value);
		
			String getMiddle();
		
			void setMiddle(String value);
		
			IUi2DAnimation getMiddleObject();
		
			void setMiddleObject(IUi2DAnimation value);
		
			int getOverlapLeft();
		
			void setOverlapLeft(int value);
		
			int getOverlapTop();
		
			void setOverlapTop(int value);
		
			int getOverlapRight();
		
			void setOverlapRight(int value);
		
			int getOverlapBottom();
		
			void setOverlapBottom(int value);
		
			}
		