package com.barbre.fiddle.elements;

/**
 * Generated by BeanBuilder for SIDL Fiddle
 */
public interface IFrame extends IClass {

	String getTexture();

	void setTexture(String value);

	IPoint getLocation();

	void setLocation(IPoint value);

	ISize getSize();

	void setSize(ISize value);

	IPoint getHotspot();

	void setHotspot(IPoint value);

	int getDuration();

	void setDuration(int value);

	IRGB[] getShading();

	void setShading(IRGB[] value);

	IRGB getShading(int index);

	void setShading(int index, IRGB value);

	IRGB[] getSpecular();

	void setSpecular(IRGB[] value);

	IRGB getSpecular(int index);

	void setSpecular(int index, IRGB value);

}