
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IGauge extends IControl {
				
			IGaugeDrawTemplate getGaugeDrawTemplate();
		
			void setGaugeDrawTemplate(IGaugeDrawTemplate value);
		
			int getEQType();
		
			void setEQType(int value);
		
			IRGB getFillTint();
		
			void setFillTint(IRGB value);
		
			boolean getDrawLinesFill();
		
			void setDrawLinesFill(boolean value);
		
			IRGB getLinesFillTint();
		
			void setLinesFillTint(IRGB value);
		
			int getTextOffsetX();
		
			void setTextOffsetX(int value);
		
			int getTextOffsetY();
		
			void setTextOffsetY(int value);
		
			int getGaugeOffsetX();
		
			void setGaugeOffsetX(int value);
		
			int getGaugeOffsetY();
		
			void setGaugeOffsetY(int value);
		
			}
		