
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IGaugeDrawTemplate extends IClass {
				
			String getBackground();
		
			void setBackground(String value);
		
			IUi2DAnimation getBackgroundObject();
		
			void setBackgroundObject(IUi2DAnimation value);
		
			String getFill();
		
			void setFill(String value);
		
			IUi2DAnimation getFillObject();
		
			void setFillObject(IUi2DAnimation value);
		
			String getLines();
		
			void setLines(String value);
		
			IUi2DAnimation getLinesObject();
		
			void setLinesObject(IUi2DAnimation value);
		
			String getLinesFill();
		
			void setLinesFill(String value);
		
			IUi2DAnimation getLinesFillObject();
		
			void setLinesFillObject(IUi2DAnimation value);
		
			String getEndCapRight();
		
			void setEndCapRight(String value);
		
			IUi2DAnimation getEndCapRightObject();
		
			void setEndCapRightObject(IUi2DAnimation value);
		
			String getEndCapLeft();
		
			void setEndCapLeft(String value);
		
			IUi2DAnimation getEndCapLeftObject();
		
			void setEndCapLeftObject(IUi2DAnimation value);
		
			}
		