
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IInvSlot extends IControl {
				
			int getEQType();
		
			void setEQType(int value);
		
			String getBackground();
		
			void setBackground(String value);
		
			IUi2DAnimation getBackgroundObject();
		
			void setBackgroundObject(IUi2DAnimation value);
		
			int getItemOffsetX();
		
			void setItemOffsetX(int value);
		
			int getItemOffsetY();
		
			void setItemOffsetY(int value);
		
			}
		