
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface ILabel extends IControl {
				
			int getEQType();
		
			void setEQType(int value);
		
			boolean getNoWrap();
		
			void setNoWrap(boolean value);
		
			boolean getAlignCenter();
		
			void setAlignCenter(boolean value);
		
			boolean getAlignRight();
		
			void setAlignRight(boolean value);
		
			}
		