
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IListbox extends IControl {
				
			IListboxColumn[] getColumns();
		
			void setColumns(IListboxColumn[] value);
		
			IListboxColumn getColumns(int index);
		
			void setColumns(int index, IListboxColumn value);
		
			boolean getOwnerDraw();
		
			void setOwnerDraw(boolean value);
		
			}
		