
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IListboxColumn extends IClass {
				
			String getHeader();
		
			void setHeader(String value);
		
			IFrameTemplate getHeaderObject();
		
			void setHeaderObject(IFrameTemplate value);
		
			String getHeading();
		
			void setHeading(String value);
		
			int getWidth();
		
			void setWidth(int value);
		
			boolean getSortable();
		
			void setSortable(boolean value);
		
			String getDataType();
		
			void setDataType(String value);
		
			}
		