
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IPage extends IControl {
				
			String getTabText();
		
			void setTabText(String value);
		
			IRGB getTabTextColor();
		
			void setTabTextColor(IRGB value);
		
			IRGB getTabTextActiveColor();
		
			void setTabTextActiveColor(IRGB value);
		
			String getTabIcon();
		
			void setTabIcon(String value);
		
			IUi2DAnimation getTabIconObject();
		
			void setTabIconObject(IUi2DAnimation value);
		
			String getTabIconActive();
		
			void setTabIconActive(String value);
		
			IUi2DAnimation getTabIconActiveObject();
		
			void setTabIconActiveObject(IUi2DAnimation value);
		
			String[] getPieces();
		
			void setPieces(String[] value);
		
			String getPieces(int index);
		
			void setPieces(int index, String value);
		
			IScreenPiece[] getPiecesObject();
		
			void setPiecesObject(IScreenPiece[] value);
		
			IScreenPiece getPiecesObject(int index);
		
			void setPiecesObject(int index, IScreenPiece value);
		
			}
		