
			package com.barbre.fiddle.elements;
			
			
	import java.awt.Point;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IPoint extends INode {
				
			int getX();
		
			void setX(int value);
		
			int getY();
		
			void setY(int value);
		
	Point getPoint();
	void setPoint(Point p);
			}
		