
			package com.barbre.fiddle.elements;
			
			
	import java.awt.Color;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IRGB extends IClass {
				
			int getAlpha();
		
			void setAlpha(int value);
		
			int getR();
		
			void setR(int value);
		
			int getG();
		
			void setG(int value);
		
			int getB();
		
			void setB(int value);
		
	Color getColor();
	void setColor(Color c);
			}
		