
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IScreenPiece extends IClass {
				
			String getScreenID();
		
			void setScreenID(String value);
		
			int getFont();
		
			void setFont(int value);
		
			boolean getRelativePosition();
		
			void setRelativePosition(boolean value);
		
			IPoint getLocation();
		
			void setLocation(IPoint value);
		
			ISize getSize();
		
			void setSize(ISize value);
		
			boolean getAutoStretch();
		
			void setAutoStretch(boolean value);
		
			boolean getTopAnchorToTop();
		
			void setTopAnchorToTop(boolean value);
		
			boolean getLeftAnchorToLeft();
		
			void setLeftAnchorToLeft(boolean value);
		
			boolean getBottomAnchorToTop();
		
			void setBottomAnchorToTop(boolean value);
		
			boolean getRightAnchorToLeft();
		
			void setRightAnchorToLeft(boolean value);
		
			int getTopAnchorOffset();
		
			void setTopAnchorOffset(int value);
		
			int getBottomAnchorOffset();
		
			void setBottomAnchorOffset(int value);
		
			int getLeftAnchorOffset();
		
			void setLeftAnchorOffset(int value);
		
			int getRightAnchorOffset();
		
			void setRightAnchorOffset(int value);
		
			String getText();
		
			void setText(String value);
		
			IRGB getTextColor();
		
			void setTextColor(IRGB value);
		
			}
		