
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IScreen extends IControl {
				
			boolean getStyle_Titlebar();
		
			void setStyle_Titlebar(boolean value);
		
			boolean getStyle_Closebox();
		
			void setStyle_Closebox(boolean value);
		
			boolean getStyle_Minimizebox();
		
			void setStyle_Minimizebox(boolean value);
		
			boolean getStyle_Sizable();
		
			void setStyle_Sizable(boolean value);
		
			String[] getPieces();
		
			void setPieces(String[] value);
		
			String getPieces(int index);
		
			void setPieces(int index, String value);
		
			IScreenPiece[] getPiecesObject();
		
			void setPiecesObject(IScreenPiece[] value);
		
			IScreenPiece getPiecesObject(int index);
		
			void setPiecesObject(int index, IScreenPiece value);
		
			}
		