
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IScrollbarDrawTemplate extends IClass {
				
			IButtonDrawTemplate getUpButton();
		
			void setUpButton(IButtonDrawTemplate value);
		
			IButtonDrawTemplate getDownButton();
		
			void setDownButton(IButtonDrawTemplate value);
		
			IFrameTemplate getThumb();
		
			void setThumb(IFrameTemplate value);
		
			String getMiddleTextureInfo();
		
			void setMiddleTextureInfo(String value);
		
			IRGB getMiddleTint();
		
			void setMiddleTint(IRGB value);
		
			}
		