
			package com.barbre.fiddle.elements;
			
			
	import java.awt.Dimension;
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface ISize extends INode {
				
			int getCX();
		
			void setCX(int value);
		
			int getCY();
		
			void setCY(int value);
		
	Dimension getSize();
	void setSize(Dimension d);
			}
		