
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface ISlider extends IControl {
				
			String getSliderArt();
		
			void setSliderArt(String value);
		
			ISliderDrawTemplate getSliderArtObject();
		
			void setSliderArtObject(ISliderDrawTemplate value);
		
			}
		