
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface ISliderDrawTemplate extends IClass {
				
			IButtonDrawTemplate getThumb();
		
			void setThumb(IButtonDrawTemplate value);
		
			String getBackground();
		
			void setBackground(String value);
		
			IUi2DAnimation getBackgroundObject();
		
			void setBackgroundObject(IUi2DAnimation value);
		
			String getEndCapRight();
		
			void setEndCapRight(String value);
		
			IUi2DAnimation getEndCapRightObject();
		
			void setEndCapRightObject(IUi2DAnimation value);
		
			String getEndCapLeft();
		
			void setEndCapLeft(String value);
		
			IUi2DAnimation getEndCapLeftObject();
		
			void setEndCapLeftObject(IUi2DAnimation value);
		
			}
		