
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface ISpellGemDrawTemplate extends IClass {
				
			String getHolder();
		
			void setHolder(String value);
		
			IUi2DAnimation getHolderObject();
		
			void setHolderObject(IUi2DAnimation value);
		
			String getBackground();
		
			void setBackground(String value);
		
			IUi2DAnimation getBackgroundObject();
		
			void setBackgroundObject(IUi2DAnimation value);
		
			String getHighlight();
		
			void setHighlight(String value);
		
			IUi2DAnimation getHighlightObject();
		
			void setHighlightObject(IUi2DAnimation value);
		
			}
		