
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface ISpellGem extends IControl {
				
			ISpellGemDrawTemplate getSpellGemDrawTemplate();
		
			void setSpellGemDrawTemplate(ISpellGemDrawTemplate value);
		
			int getSpellIconOffsetX();
		
			void setSpellIconOffsetX(int value);
		
			int getSpellIconOffsetY();
		
			void setSpellIconOffsetY(int value);
		
			}
		