
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IStaticScreenPiece extends IScreenPiece {
				
			boolean getAutoDraw();
		
			void setAutoDraw(boolean value);
		
			}
		