
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IStaticHeader extends IStaticScreenPiece {
				
			String getFrameTemplate();
		
			void setFrameTemplate(String value);
		
			IFrameTemplate getFrameTemplateObject();
		
			void setFrameTemplateObject(IFrameTemplate value);
		
			String getTextReference();
		
			void setTextReference(String value);
		
			IRGB getTextColor();
		
			void setTextColor(IRGB value);
		
			}
		