
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IStaticFrame extends IStaticScreenPiece {
				
			String getFrameTemplate();
		
			void setFrameTemplate(String value);
		
			IFrameTemplate getFrameTemplateObject();
		
			void setFrameTemplateObject(IFrameTemplate value);
		
			}
		