
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IStaticAnimation extends IStaticScreenPiece {
				
			String getAnimation();
		
			void setAnimation(String value);
		
			IUi2DAnimation getAnimationObject();
		
			void setAnimationObject(IUi2DAnimation value);
		
			}
		