
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface ISuiteDefaults extends IClass {
				
			String getDefaultWindowDrawTemplate();
		
			void setDefaultWindowDrawTemplate(String value);
		
			IWindowDrawTemplate getDefaultWindowDrawTemplateObject();
		
			void setDefaultWindowDrawTemplateObject(IWindowDrawTemplate value);
		
			String getCursorDefault();
		
			void setCursorDefault(String value);
		
			IUi2DAnimation getCursorDefaultObject();
		
			void setCursorDefaultObject(IUi2DAnimation value);
		
			String getCursorResizeNS();
		
			void setCursorResizeNS(String value);
		
			IUi2DAnimation getCursorResizeNSObject();
		
			void setCursorResizeNSObject(IUi2DAnimation value);
		
			String getCursorResizeEW();
		
			void setCursorResizeEW(String value);
		
			IUi2DAnimation getCursorResizeEWObject();
		
			void setCursorResizeEWObject(IUi2DAnimation value);
		
			String getCursorResizeNESW();
		
			void setCursorResizeNESW(String value);
		
			IUi2DAnimation getCursorResizeNESWObject();
		
			void setCursorResizeNESWObject(IUi2DAnimation value);
		
			String getCursorResizeNWSE();
		
			void setCursorResizeNWSE(String value);
		
			IUi2DAnimation getCursorResizeNWSEObject();
		
			void setCursorResizeNWSEObject(IUi2DAnimation value);
		
			String getCursorDrag();
		
			void setCursorDrag(String value);
		
			IUi2DAnimation getCursorDragObject();
		
			void setCursorDragObject(IUi2DAnimation value);
		
			}
		