
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface ITabBox extends IControl {
				
			String getTabBorderTemplate();
		
			void setTabBorderTemplate(String value);
		
			IFrameTemplate getTabBorderTemplateObject();
		
			void setTabBorderTemplateObject(IFrameTemplate value);
		
			String getPageBorderTemplate();
		
			void setPageBorderTemplate(String value);
		
			IFrameTemplate getPageBorderTemplateObject();
		
			void setPageBorderTemplateObject(IFrameTemplate value);
		
			String[] getPages();
		
			void setPages(String[] value);
		
			String getPages(int index);
		
			void setPages(int index, String value);
		
			IPage[] getPagesObject();
		
			void setPagesObject(IPage[] value);
		
			IPage getPagesObject(int index);
		
			void setPagesObject(int index, IPage value);
		
			}
		