
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface ITextureInfo extends IClass {
				
			ISize getSize();
		
			void setSize(ISize value);
		
			}
		