
			package com.barbre.fiddle.elements;
			
			
			
			/**
			 * Generated by BeanBuilder for SIDL Fiddle
			 */
			public interface IWindowDrawTemplate extends IClass {
				
			String getBackground();
		
			void setBackground(String value);
		
			ITextureInfo getBackgroundObject();
		
			void setBackgroundObject(ITextureInfo value);
		
			IScrollbarDrawTemplate getVSBTemplate();
		
			void setVSBTemplate(IScrollbarDrawTemplate value);
		
			IScrollbarDrawTemplate getHSBTemplate();
		
			void setHSBTemplate(IScrollbarDrawTemplate value);
		
			IButtonDrawTemplate getCloseBox();
		
			void setCloseBox(IButtonDrawTemplate value);
		
			IButtonDrawTemplate getMinimizeBox();
		
			void setMinimizeBox(IButtonDrawTemplate value);
		
			IButtonDrawTemplate getTileBox();
		
			void setTileBox(IButtonDrawTemplate value);
		
			IFrameTemplate getBorder();
		
			void setBorder(IFrameTemplate value);
		
			IFrameTemplate getTitlebar();
		
			void setTitlebar(IFrameTemplate value);
		
			}
		